# Generated by Django 5.2.14 on 2026-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, default='Unknown Patient', max_length=255)),
                ('image', models.ImageField(upload_to='diagnoses/')),
                ('prediction', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('glaucoma_prob', models.FloatField(default=0.0)),
                ('normal_prob', models.FloatField(default=0.0)),
                ('doctor_notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
