# Generated by Django 5.2.9 on 2026-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctor_specialist_diagnosis_patient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='model_used',
            field=models.CharField(default='ViT', max_length=50),
        ),
    ]
